### PR TITLE
Autotools

### PR DESCRIPTION
**Pull request by rajesh6115**
1. Introducing Autotools build system
for Install we have simply do below steps
autoreconf -iv
./configure
make
make install

2. Also removed smpp_pdu_pack_real dependency by adding a static function smpp_pdu_pack_without_command_length

### CODE REVIEW

**Comment by rajesh6115** [comment]
I think kannel 1.4.5 release taken care of both TLV memory leak problems and load_*  changes

**Comment by ib1corp** [comment]
SUB: cannot install using autoconf if kannel path is different!!!

Im having difficulty in installing ksmppd using the autoconf / make / install script if the kannel directory/path is in a different location.

My kannel installation had a dir prefix /usr/local/kannel/

When i try to install ksmppd, it get this errir:
Please install kannel gw-config before installing.

If i install kannel without any prefix and then try to install ksmppd it works.
I tried to prefix dir while installing ksmppd but that also does not work.

How do we use the autoconf script to install ksmppd if kannel is not install in default location?

can u please help.

**Comment by rajesh6115** [comment]
maybe kennel exec location(**/usr/local/kannel/bin**) not in your **PATH** environment.  autotools fetch required information of kannel installation from gw-config binary, and which is a part of kannel package itself.
you can make sure by **which gw-config** to see where gw-config is installed.

**Comment by ib1corp** [comment]
I had installed kannel here : /usr/local/kannel/ so the path for gw-config was /usr/local/kannel/bin, with this path im getting error "Please install kannel gw-config before installing." when trying to install ksmppd.

I i install kannel here :  /usr/local/kannel/bin then ksmppd is isntalling properly.

While installing ksmppd How to specify the PATH where kannel is installed, if its not the default location?

**Comment by veduyu** [comment]
@rajesh6115 iam gtting the following error when i tried to install with auticonf

root@ubuntu-s-4vcpu-8gb-blr1-01:/opt/ksmppd-master# autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
aclocal: warning: couldn't open directory 'm4': No such file or directory
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
libtoolize: 'AC_PROG_RANLIB' is rendered obsolete by 'LT_INIT'
autoreconf: running: /usr/bin/autoconf
autoreconf: running: /usr/bin/autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:19: installing 'build-aux/ar-lib'
configure.ac:12: installing 'build-aux/compile'
configure.ac:24: installing 'build-aux/config.guess'
configure.ac:24: installing 'build-aux/config.sub'
configure.ac:8: installing 'build-aux/install-sh'
configure.ac:8: installing 'build-aux/missing'
automake: error: no 'Makefile.am' found for any configure output
autoreconf: automake failed with exit status: 1

**Comment by donald-jackson** [comment]
Hi @rajesh6115 any chance you could update these changes to the latest version, would be good to get auto conf in

**Comment by rajesh6115** [comment]
Hi @donald-jackson I will update the changes to the latest master branch, and updated the pull request

**Comment by rajesh6115** [comment]
Hi, @donald-jackson I can see using auto tools it is not compiled, as your code is referring to svn revision 5297. 
but kannel gateway version 1.4.5 (stable) has **regex.h** and in code **gw-regex.h** used. 

So are we going with dev version of kannel gateway?
I have just compiled after modifying gw-regex.h to regex.h, It's compiled successfully without any issue.

**Pull request merged**
